### ISSUE TITLE
problems with error

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#130] opened 2017-06-09 09:27 UTC
Using the latest release I can no longer build - issues with errors.h macro expansion ... any ideas please?

`1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(50): error C2121: '#': invalid character: possibly the result of a macro expansion
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(17): error C2059: syntax error: 'if'
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(17): error C2059: syntax error: 'public'
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(50): error C2143: syntax error: missing ';' before '{'
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(50): error C2447: '{': missing function header (old-style formal list?)
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(17): error C2143: syntax error: missing ';' before 'if'
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(51): error C2143: syntax error: missing ';' before '<class-head>'
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(85): error C2121: '#': invalid character: possibly the result of a macro expansion
1>c:\activewords4\activewords dll\sqlite_modern_cpp\lists\error_codes.h(81): error C2059: syntax error: 'if'
`

**Comment by zauguin** [comment] 2017-06-10 11:25
Is this problem fixed with #128?

**Comment by mtissington** [comment] 2017-06-10 11:56
I'm using Visual Studio 2017 to build - I believe the equivalent is /permissive- switch.
Unfortunately it is not fixed.

**Comment by zauguin** [comment] 2017-06-11 00:43
@mtissington That's odd. I tried compiling with Visual Studio 2017 and I got the same errors with the release, but they are fixed with #128.
Do you still get the same error messages after applying the patch?

**Comment by mtissington** [comment] 2017-06-16 07:48
Sorry for the late reply - missed a notification. 

I assumed the patch had been merged (which now you have) and can confirm it works.
I do now get lots of warning about case statements which I presume can be ignored?

**Comment by zauguin** [comment] 2017-07-12 13:18
Yes, they can be ignored. They are caused by automatically generated switch statements.

**Closed by zauguin** 2017-07-12 13:18 UTC
